version: 2.0.{build}
configuration: Release
image: Visual Studio 2017
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- nuget restore LongPath.sln
build:
  project: LongPath.sln
after_build:
- cmd: >-
    if not exist nuget\lib\net40 md nuget\lib\net40

    copy Pri.LongPath.net40\bin\Release\Pri.LongPath.dll nuget\lib\net40

    copy Pri.LongPath.net40\bin\Release\Pri.LongPath.pdb nuget\lib\net40

    if not exist nuget\lib\net20 md nuget\lib\net20

    copy Pri.LongPath.net20\bin\Release\Pri.LongPath.dll nuget\lib\net20

    copy Pri.LongPath.net20\bin\Release\Pri.LongPath.pdb nuget\lib\net20

    if not exist nuget\lib\net45 md nuget\lib\net45

    copy Pri.LongPath\bin\Release\Pri.LongPath.dll nuget\lib\net45

    copy Pri.LongPath\bin\Release\Pri.LongPath.pdb nuget\lib\net45


    nuget.exe pack nuget\LongPath.nuspec -Symbols -version %APPVEYOR_BUILD_VERSION%
